### ISSUE TITLE
Fehlermeldungen

### ISSUE THREAD

**Issue by dslraser** [BasGo/ioBroker.places#2]
Hallo,
ich erhalte seit heute in regelmäßigen Abständen Fehlermeldungen im Log.

places.0 | 2018-08-21 11:21:37.193 | error | Error while requesting elevation: "timeout"
-- | -- | -- | --
places.0 | 2018-08-21 11:21:37.177 | error | Error while requesting elevation: "timeout"
places.0 | 2018-08-21 11:20:37.192 | error | Error while requesting address: "timeout"
places.0 | 2018-08-21 11:20:37.175 | error | Error while requesting address: "timeout"
places.0 | 2018-08-21 11:20:36.634 | error | Error while requesting route: "timeout"
places.0 | 2018-08-21 11:20:36.610 | error | Error while requesting route: "timeout"

**Comment by dslraser** [comment]
läuft wieder, keine Ahnung warum es so war.....

**Comment by dslraser** [comment]
ich habe doch immer wieder die oben aufgeführte Fehlermeldung. Es wird zwar richtig erkannt das zwei Personen (mehr nutze ich nicht) in der "Homezone" sind aber es werden keine Adressen geschrieben und dann folgen die Meldungen im Log

**Comment by BasGo** [comment]
Kann es mitunter sein, dass du zu viele Änderungen von Positionen verarbeiten lässt? Leider weiß ich nicht genau, wo das Limit bei Google liegt, aber laut Netz kommt diese Timeout-Meldung auch, wenn das Limit an Anfragen für einen gewissen Zeitraum ausgereizt wurde (was ja dafür spricht, dass es mal geht und mal nicht).

**Comment by dslraser** [comment]
die Koordinaten kommen immer, aber es kommen keine Adressen mehr dazu an. (aber auch keine Fehlermeldungen mehr). Auch die anderen Felder  im Anhang bleiben leer
![places](https://user-images.githubusercontent.com/32881445/44985723-9ded0b80-af81-11e8-8f81-6693b9e8c869.JPG)
![p2](https://user-images.githubusercontent.com/32881445/44985779-d1c83100-af81-11e8-9d85-7ad8b1461ce4.JPG)
Der Rest klappt tadellos

**Comment by BasGo** [comment]
Genau das scheint ja bei dir das Problem zu sein:

Der Adapter ist so aufgebaut, dass Dinge wie die Adressermittlung (per Google) rein **optional** sind und keinen Einfluss auf die Umkreiserkennung (die rein mathematisch auf Basis der Koordinaten und Umkreise erfolgt) haben. Und genau diese Adressermittlung ist das Problem bei dir.

Leider kann ich im Moment nicht sagen, weshalb die Adressermittlung von Google einen **Error while requesting route: "timeout"** zurückgibt. Hast du einen **eigenen Google-Key** eingetragen oder den von ioBroker (Maps-Adapter für VIS) übernommen? Weil: dieser Timeout-Fehler wird auch dann zurückgegeben, wenn die Requests ein Limit von 50 Anfragen pro Sekunde überschreiten ... was im Falle eines übernommenen Keys durchaus sein könnte :-(

**Comment by dslraser** [comment]
ich hatte mal einen eigenen Google Key (zu Anfang, hatte mich da probeweise angemeldet, da es aber kostenpflichtig ist/wird, wieder beendet) Den habe ich jetzt nicht mehr. VIS nutze ich nicht, werde es aber mal installieren.

**Comment by dslraser** [comment]
vielleicht hat es auch damit zu tun ?
(ich bin nicht der Einzige der diesen Fehler hat, der ist schon bekannt)
![maps](https://user-images.githubusercontent.com/32881445/44993381-ac93ec80-af9a-11e8-9227-07fe5ce758d0.JPG)
![maps2](https://user-images.githubusercontent.com/32881445/44993385-af8edd00-af9a-11e8-8bff-8fdddfacefe3.JPG)

)

**Comment by GermanBluefox** [comment]
>vielleicht hat es auch damit zu tun ?

Wir bauen das auf Open Street Map.

**Comment by BasGo** [comment]
Für den Moment müssen wir die Adressermittlung demnach als Nice-To-Have betrachten: in der Regel funktioniert sie, aber eine Garantie gibt es leider nicht. Soweit ich mich erinnern kann, würde auch ein weiteres Logging nicht helfen, weil Google hier einfach nicht mehr Informationen zur Verfügung stellt.

Wichtig ist, dass die Auswertung des Orts (zuhause oder in einem anderen definierten Bereich) funktioniert. Ich werde das Thema aber im Auge behalten ;-)

**Comment by dslraser** [comment]
Danke, ja genau so sehe ich das im auch. Für meine Zwecke läuft alles und das Prima 👍
